go:
    # Whenever the Go version is updated here,
    # .circle/config.yml should also be updated.
    version: 1.23
repository:
    path: github.com/prometheus/promlens
build:
    binaries:
        - name: promlens
          path: ./cmd/promlens
    flags: -a -tags netgo,builtinassets
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    # Whenever there are new files to include in the tarball,
    # remember to make sure the new files will be generated after `make build`.
    files:
        - LICENSE
        - NOTICE
        - npm_licenses.tar.bz2
crossbuild:
    platforms:
        - darwin
        - freebsd
        - linux/386
        - linux/amd64
        - linux/arm
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
        - netbsd/amd64
        - windows/amd64
        - windows/arm64
