export const functionArgNames: Record<string, string[]> = {
  // abs: ['value'],
  // absent: [],
  // absent_over_time: [],
  // avg_over_time: [],
  // ceil: [],
  // changes: [],
  clamp: ['input series', 'min', 'max'],
  // clamp_max: [],
  // clamp_min: [],
  // count_over_time: [],
  day_of_month: ['timestamp (default = vector(time()))'],
  day_of_week: ['timestamp (default = vector(time()))'],
  day_of_year: ['timestamp (default = vector(time()))'],
  days_in_month: ['timestamp (default = vector(time()))'],
  // delta: [],
  // deriv: [],
  double_exponential_smoothing: ['input series', 'smoothing factor', 'trend factor'],
  // exp: [],
  // floor: [],
  histogram_fraction: ['lower bound', 'upper bound', 'histogram'],
  histogram_quantile: ['target quantile', 'histogram'],
  histogram_quantiles: ['histogram', 'quantile label name', 'target quantile'],
  hour: ['timestamp (default = vector(time()))'],
  info: ['input series', 'data label selector (optional)'],
  // idelta: [],
  // increase: [],
  // irate: [],
  label_join: ['series', 'destination label', 'separator', 'source label'],
  label_replace: ['input series', 'destination label', 'replacement', 'source label', 'regex'],
  // ln: [],
  // log10: [],
  // log2: [],
  // max_over_time: [],
  // min_over_time: [],
  minute: ['timestamp (default = vector(time()))'],
  month: ['timestamp (default = vector(time()))'],
  predict_linear: ['input series', 'duration from now [s]'],
  quantile_over_time: ['target quantile', 'input series'],
  // rate: [],
  // resets: [],
  round: ['input series', 'to nearest (default = 1)'],
  sort_by_label: ['input series', 'label name'],
  sort_by_label_desc: ['input series', 'label name'],
  // scalar: [],
  // sort: [],
  // sort_desc: [],
  // sqrt: [],
  // stddev_over_time: [],
  // stdvar_over_time: [],
  // sum_over_time: [],
  // time: [],
  // timestamp: [],
  // vector: [],
  year: ['timestamp (default = vector(time()))'],
};

export const functionDescriptions: Record<string, string> = {
  abs: 'return absolute values of input series',
  absent: 'determine whether input vector is empty',
  absent_over_time: 'determine whether input range vector is empty',
  avg_over_time: 'average series values over time',
  ceil: 'round up values of input series to nearest integer',
  changes: 'return number of value changes in input series over time',
  clamp: 'limit the value of input series to a certain range',
  clamp_max: 'limit the value of input series to a maximum',
  clamp_min: 'limit the value of input series to a minimum',
  count_over_time: 'count the number of values for each input series',
  day_of_month: 'return the day of the month for provided timestamps',
  day_of_week: 'return the day of the week for provided timestamps',
  day_of_year: 'return the day of the year for provided timestamps',
  days_in_month: 'return the number of days in current month for provided timestamps',
  delta: 'calculate the difference between beginning and end of a range vector (for gauges)',
  deriv: 'calculate the per-second derivative over series in a range vector (for gauges)',
  double_exponential_smoothing: 'calculate smoothed value of input series',
  end: 'return the end timestamp of the current query',
  exp: 'calculate exponential function for input vector values',
  first_over_time: 'get the first sample value from a time range',
  floor: 'round down values of input series to nearest integer',
  histogram_avg: 'calculate the average observed value from a native histogram',
  histogram_count: 'return the count of observations from a native histogram',
  histogram_fraction: 'estimate the fraction of observations between two bounds in a histogram',
  histogram_quantile: 'calculate quantiles from histogram buckets',
  histogram_quantiles: 'calculate multiple quantiles from a histogram',
  histogram_stddev: 'estimate the standard deviation of observations in a native histogram',
  histogram_stdvar: 'estimate the standard variance of observations in a native histogram',
  histogram_sum: 'return the sum of observations from a native histogram',
  hour: 'return the hour of the day for provided timestamps',
  info: 'add data labels from matching info metrics to input series',
  idelta: 'calculate the difference between the last two samples of a range vector (for counters)',
  increase: 'calculate the increase in value over a range of time (for counters)',
  irate: 'calculate the per-second increase over the last two samples of a range vector (for counters)',
  label_join: 'join together label values into new label',
  label_replace: 'set or replace label values',
  last_over_time: 'get the last sample value from a time range',
  ln: 'calculate natural logarithm of input series',
  log10: 'calulcate base-10 logarithm of input series',
  log2: 'calculate base-2 logarithm of input series',
  mad_over_time: 'calculate the median absolute deviation of input series over time',
  max_of: 'return the larger of two scalar values',
  max_over_time: 'return the maximum value over time for input series',
  min_of: 'return the smaller of two scalar values',
  min_over_time: 'return the minimum value over time for input series',
  minute: 'return the minute of the hour for provided timestamps',
  month: 'return the month for provided timestamps',
  predict_linear: 'predict the value of a gauge into the future',
  present_over_time: 'return 1 for any input series present in a time range',
  quantile_over_time: 'calculate value quantiles over time for input series',
  range: 'return the range duration of the current query in seconds',
  rate: 'calculate per-second increase over a range vector (for counters)',
  resets: 'return number of value decreases (resets) in input series of time',
  round: 'round values of input series to nearest integer',
  scalar: 'convert single-element series vector into scalar value',
  sgn: 'return the sign of the input value (-1, 0, or 1)',
  sort: 'sort input series ascendingly by value',
  sort_by_label: 'sort input series ascendingly by label values',
  sort_by_label_desc: 'sort input series descendingly by label values',
  sort_desc: 'sort input series descendingly by value',
  sqrt: 'return the square root for input series',
  start: 'return the start timestamp of the current query',
  stddev_over_time: 'calculate the standard deviation within input series over time',
  stdvar_over_time: 'calculate the standard variation within input series over time',
  step: 'return the query resolution step in seconds',
  sum_over_time: 'calculate the sum over the values of input series over time',
  time: 'return the Unix timestamp at the current evaluation time',
  timestamp: 'return the Unix timestamp for the samples in the input vector',
  ts_of_first_over_time: 'return the timestamp of the first sample in a time range',
  ts_of_last_over_time: 'return the timestamp of the last sample in a time range',
  ts_of_max_over_time: 'return the timestamp of the maximum sample in a time range',
  ts_of_min_over_time: 'return the timestamp of the minimum sample in a time range',
  vector: 'convert a scalar value into a single-element series vector',
  year: 'return the year for provided timestamps',
};
